<?php
// Build the menue
  $url_basis  = $_SESSION['SITE']['site_url'];
  $menue = '';
  $url_txt_0 = MENUE_HOME;
  $url_link_0 = $url_basis.'home';
  $menue.= '<a href="'.$url_link_0.'">'.$url_txt_0.'</a>';
if ($_SESSION['SITE']['access']=='true'){
  $url_link_dash = $url_basis.'dashboard';
  $menue.= '<a href="'.$url_link_dash.'">Dashboard</a>';
}
?>
<head>
<!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="description" content="<?php echo SITE_DESCRIPTION; ?>">
  <meta name="keywords" content="<?php echo SITE_KEYWORDS; ?>">
  <meta name="author" content="<?php echo SITE_AUTHOR; ?>">
  <meta name="system" content="<?php echo php_uname('n'); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="index, nofollow" />
  <title><?php echo SITE_NAME; ?></title>
<!--.Bootstrap & Frameworks CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="<?php echo $_SESSION['SITE']['site_url']; ?>cdn/css/default.css" >
<!--.JavaScripts--------------------->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>

<!--.Others------------------->
  <link rel="icon" href="<?php echo $_SESSION['SITE']['site_url']; ?>favicon.ico" type="image/x-icon" />
</head>
<body>
<!--.Navbar--->
<div class="topnav">
  <img src="<?php echo $_SESSION['SITE']['site_url']; ?>cdn/img/1kosmos-logo.png" alt="1Kosmos" style="height:24px; vertical-align:middle; margin:8px 12px;">
  <?php echo $menue ?>
</div>
<!--/.Header--->
<div id="container">