<?php
// Build the menue
  $url_basis  = $_SESSION['SITE']['site_url'];
  $menue = '';
  $url_txt_0 = MENUE_HOME;
  $url_link_0 = $url_basis.'home';
  $menue.= '<a href="'.$url_link_0.'">'.$url_txt_0.'</a>';
if ($_SESSION['SITE']['access']=='true'){
  $url_txt_1 = MENUE_ONE;
  $url_link_1 = $url_basis.'one';
  $menue.= '<a href="'.$url_link_1.'">'.$url_txt_1.'</a>';
  $url_txt_2 = MENUE_TWO;
  $url_link_2 = $url_basis.'two';
  $menue.= '<a href="'.$url_link_2.'">'.$url_txt_2.'</a>';
  $url_txt_3 = MENUE_THREE;
  $url_link_3 = $url_basis.'three';
  $menue.= '<a href="'.$url_link_3.'">'.$url_txt_3.'</a>';
  $url_txt_4 = MENUE_FOUR;
  $url_link_4 = $url_basis.'four';
  $menue.= '<a href="'.$url_link_4.'">'.$url_txt_4.'</a>';
}
?>
<head>
<!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="description" content="<?php echo SITE_DESCRIPTION; ?>">
  <meta name="keywords" content="<?php echo SITE_KEYWORDS; ?>">
  <meta name="author" content="<?php echo SITE_AUTHOR; ?>">
  <meta name="system" content="<?php echo php_uname('n'); ?>" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="index, nofollow" />
  <title><?php echo SITE_NAME; ?></title>
<!--.Bootstrap & Frameworks CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="<?php echo $_SESSION['SITE']['site_url']; ?>cdn/css/default.css" >
<!--.JavaScripts--------------------->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.js" integrity="sha512-6DC1eE3AWg1bgitkoaRM1lhY98PxbMIbhgYCGV107aZlyzzvaWCW1nJW2vDuYQm06hXrW0As6OGKcIaAVWnHJw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

<!--.Others------------------->
  <link rel="icon" href="<?php echo $_SESSION['SITE']['site_url']; ?>favicon.ico" type="image/x-icon" />
</head>
<body>
<!--.Navbar--->
<div class="topnav">
  <?php echo $menue ?>
</div>
<!--/.Header--->
<div id="container">
