<?php
?>
<div id="form_container">
  <div class="page_title"><?php echo PAGE_THREE_TITLE; ?></div>
    <div class="page_content"><?php echo PAGE_THREE_CONTENT_1; ?></div>
    <div class="page_content"><?php echo PAGE_THREE_CONTENT_2; ?></div>
    <br>
    <form action="/" method="post">
      <input name="do" value="pwless" type="hidden">
      <button type="submit" class="btn btn-primary">Passwordless Login</button>
    </form>
</div>
