<?php
?>
<div id="form_container">
  <div class="page_title"><?php echo PAGE_TWO_TITLE; ?></div>
    <div class="page_content"><?php echo PAGE_TWO_CONTENT_1; ?></div>
    <div class="page_content"><?php echo PAGE_TWO_CONTENT_2; ?></div>
    <br>
    <form action="/" method="post">
      <input name="do" value="reset" type="hidden">
      <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" name="email" required>
      </div>
      <br>
      <button type="submit" class="btn btn-primary">Reset Password</button>
    </form>
</div>
